### ISSUE TITLE
Extra volume mounts

### ISSUE THREAD

**Issue by phoenix-bjoern** [softonic/varnish-chart#29]
Varnish can use disk storage as "extended cache storage" e.g. for streaming purposes or media file caching. You can simply define it with additional command arguments in the chart:

```
    varnishSize: 128M
    arguments:
      - -s
      - images=file,/tmp/varnish-image-cache,10g
```

`varnishSize` is the memory/RAM allocated for the default Varnish cache. `images` is the name/alias for a 10g file on disk (`/tmp/varnish-image-cache`). Cacheable objects can be saved in this file-based cache with a small VCL snippet like:

```
        sub vcl_backend_response {
            if (beresp.ttl > 0s && bereq.http.x-img-processing == "1") {
                set beresp.storage = storage.images;
            }
}
```

With that you don't waste expensive memory for big files but still can cache and deliver it by Varnish.

In the example above the cache file is created in the `/tmp` directory of the container which actually means it allocates 10g in the container engine's ephemeral data directory (e.g. /var/lib/docker). To save it in an emptyDir or even in a persistent storage the chart should support "extra volume mounts".

**Comment by phoenix-bjoern** [comment]
Closing this issue. If necessary we can continue discussion in PR #30.

**Comment by phoenix-bjoern** [comment]
Sorry, I fear I introduced a bug, not sure why.

Steps to reproduce:
1. Add this for values.yaml
```
extraVolumes:
  - name: disk-cache
    emptyDir: {}

extraVolumeMounts:
  - name: disk-cache
    mountPath: /mnt
```

2. Run `helm template . `. The following error will occur:
```
Error: YAML parse error on varnish/templates/deployment.yaml: error converting YAML to JSON: yaml: line 57: did not find expected key
```
3. Lower the nindent in `templates/deployment.yaml`:
```
diff --git a/templates/deployment.yaml b/templates/deployment.yaml
index 9d173d9..53144e4 100644
--- a/templates/deployment.yaml
+++ b/templates/deployment.yaml
@@ -79,7 +79,7 @@ spec:
             mountPath: /etc/varnish
           {{- end }}
           {{- if .Values.extraVolumeMounts }}
-          {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
+          {{- toYaml .Values.extraVolumeMounts | nindent 10 }}
           {{- end }}
           {{- with .Values.livenessProbe }}
           livenessProbe:
@@ -157,7 +157,7 @@ spec:
       {{- end }}
       {{- end }}
       {{- if .Values.extraVolumes }}
-        {{- toYaml .Values.extraVolumes | nindent 8 }}
+        {{- toYaml .Values.extraVolumes | nindent 6 }}
       {{- end }}
     {{- end }}
```

@santinoncs can you reproduce this issue?

**Comment by santinoncs** [comment]
Also this error when enabling extraVolumes...

```
Error: YAML parse error on varnish/templates/deployment.yaml: error converting YAML to JSON: yaml: line 54: did not find expected key
```

After your modification everything works

**Comment by phoenix-bjoern** [comment]
Thanks @santinoncs for cross checking.
Created PR #32 and raised the version number. Closing this issue.

**Comment by santinoncs** [comment]
Thanks to you @phoenix-bjoern !
